Repository lxndrblz/anatole, pull requests merged in 2022-01, with the labels that each got.

#287 fix: overlap on ultra wide screens
  assets/css/style.css
Labels: bug

#289 added english aria labels for prev/next
  layouts/partials/pagination.html
Labels: enhancement, good first issue

#290 Fixing typos
  README.md
  exampleSite/content/english/about.md
  i18n/de.toml
Labels: documentation

#293 README.md: adding links to config .toml and example site
  README.md
Labels: documentation

#296 Add option to use Plausible Analytics
  README.md
  exampleSite/config/_default/params.toml
  layouts/partials/analytics/plausible.html
  layouts/partials/head.html
Labels: enhancement
