Repository lxndrblz/anatole, pull requests merged in 2024-07, with the labels that each got.

#510 chore: update dependencies
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  package-lock.json
Labels: dependencies

#507 fix: remove decoration around backtick blocks
  assets/scss/partials/components/_post.scss
Labels: bug

#473 feat: translate related posts header
  i18n/ar.toml
  i18n/de.toml
  i18n/dk.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fa.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hu.toml
  i18n/id.toml
  i18n/it.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/pt-PT.toml
  i18n/pt-br.toml
  i18n/tr.toml
  i18n/zh-cn.toml
  i18n/zh-tw.toml
  layouts/partials/related.html
Labels: enhancement

#487 fix: Sidebar Title Changing Margin Size Between Home Page and Others
  assets/scss/partials/components/_sidebar.scss
  layouts/partials/sidebar.html
Labels: bug

#511 fix: deprecation warnings for recent Hugo versions
  .devcontainer/Dockerfile
  exampleSite/config/_default/config.toml
  exampleSite/content/english/post/rich-content.md
  layouts/_default/single.html
  layouts/partials/footer.html
  netlify.toml
Labels: enhancement

#464 Fix warning when using hugo v0.112+
  exampleSite/config/_default/languages.toml
Labels: enhancement

#408 feat: add config option to disable title capitalization
  assets/scss/partials/components/_archive.scss
  layouts/_default/list.html
  layouts/_default/single.html
Labels: enhancement
