Repository lxndrblz/anatole, pull requests merged in 2024-04, with the labels that each got.

#497 fix: wordwrap in (un)ordered list
  assets/scss/partials/components/_post.scss
Labels: bug

#498 fix: remove async version of Google Analytics
  layouts/partials/footer.html
Labels: enhancement

#478 Tidy <head> elements
  layouts/partials/head.html
Labels: enhancement

#499 chore: bump npm package versions
  package-lock.json
  package.json
Labels: updates

#500 feat: add matomo analytics support
  layouts/partials/analytics/matomo.html
  layouts/partials/head.html
Labels: enhancement

#501 chore: explicitly list prettier plugins
  .prettierrc
Labels: dependencies
