Repository lxndrblz/anatole, pull requests merged in 2025-04, with the labels that each got.

#542 fix: clear warnings when previewing example site (hugo 0.144.2)
  exampleSite/config/_default/hugo.toml
  exampleSite/content/english/post/rich-content.md
Labels: bug

#553 Fix theme switcher
  assets/js/anatole-theme-switcher.js
Labels: bug

#545 Fix regression by planify post content on index
  layouts/index.html
Labels: bug

#538 Add support for Meta Pixel tracker
  layouts/partials/analytics/meta.html
  layouts/partials/head.html
Labels: enhancement

#518 feat: add license metadata
  exampleSite/config/_default/params.toml
  layouts/partials/head.html
  layouts/partials/schema.html
Labels: bug, enhancement

#554 chore: update NPM packages
  netlify.toml
  package-lock.json
Labels: updates
